package ar.edu.utn.dds.k3003.app;

public enum SubState {
    START,
    WAITING_RESPONSE,
    WAITING_RESPONSE_OPTION,
    WAITING_RESPONSE_QUANTITY,
    WAITING_RESPONSE_STATE,
    WAITING_RESPONSE_LINE,
    WAITING_RESPONSE_STATION,
}
